# Generated by Django 4.0.1 on 2022-04-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='titulo',
            new_name='Titulo',
        ),
        migrations.AlterField(
            model_name='servicios',
            name='Imagen',
            field=models.ImageField(upload_to='Servicios'),
        ),
    ]
